// <auto-generated />
namespace ScheduleCalendar_V2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class revrtChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(revrtChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201812111344083_revrtChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
